# Generated by Django 5.2.16 on 2026-09-26 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_semester_registration_deadline'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='projects.projectgroup'),
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CLASS_WIDE', 'Class-wide (grouped)'), ('GROUP_SPECIFIC', 'Assigned to one group')], db_index=True, default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_project_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassDelegate',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_delegates', to=settings.AUTH_USER_MODEL)),
                ('course_offering', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_delegate', to='academics.courseoffering')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_delegate_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'class delegate',
                'verbose_name_plural': 'class delegates',
            },
        ),
    ]
