# Generated by Django 6.0.6 on 2026-09-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricule',
            field=models.CharField(blank=True, db_index=True, help_text='Student matricule number (assigned on enrollment).', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staffid',
            field=models.CharField(blank=True, db_index=True, help_text='Staff / employee number (assigned by administration).', max_length=50, null=True, unique=True),
        ),
    ]
