# Generated by Django 6.1 on 2026-09-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
