# Generated by Django 6.0.6 on 2026-09-10 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=255)),
                ('actor_id', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_audit_event',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id', 'timestamp'], name='core_audit__resourc_5f739b_idx')],
            },
        ),
    ]
