# Generated by Django 6.1 on 2026-08-26 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classdefinition',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_definitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsession',
            name='class_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.classdefinition'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academics.academicperiod'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.course'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offering_lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classdefinition',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_definitions', to='academics.courseoffering'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academics.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.courseoffering'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'academic_period')},
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course_offering'), name='unique_enrollment'),
        ),
    ]
