# Generated by Django 5.2.16 on 2026-08-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_carryoverapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicPeriod',
            new_name='Semester',
        ),
        migrations.AlterModelOptions(
            name='courseoffering',
            options={'ordering': ['-semester__academic_year', 'course__code']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-academic_year', 'number']},
        ),
        migrations.RenameField(
            model_name='courseoffering',
            old_name='academic_period',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='number',
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'number')},
        ),
    ]
