# Generated by Django 6.1 on 2026-09-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_rename_academicperiod_to_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
