# Generated by Django 5.2.15 on 2026-09-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_add_is_active_to_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
