# Generated by Django 5.2.16 on 2026-09-26 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_semester_registration_deadline'),
        ('learning', '0002_assignment_assignmentsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('CA', 'Continuous Assessment'), ('EXAM', 'Exam')], default='CA', max_length=10)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_sheets', to='learning.uploadedfile')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.courseoffering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentMark',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('dispute_status', models.CharField(choices=[('NONE', 'No dispute'), ('OPEN', 'Awaiting lecturer'), ('RESOLVED', 'Resolved')], db_index=True, default='NONE', max_length=10)),
                ('dispute_reason', models.TextField(blank=True, default='')),
                ('dispute_response', models.TextField(blank=True, default='')),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='learning.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'student'), name='unique_assessment_mark')],
            },
        ),
    ]
