# Generated by Django 5.2.16 on 2026-09-26 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_semester_registration_deadline'),
        ('learning', '0003_assessment_assessmentmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='group_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Share of the group grade this assessment carries (percent). Leave blank to split the group evenly between its members.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='raw_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Scale the lecturer actually marks on (e.g. 20 while the assessment is reported out of 30). Empty means marks are entered directly on the reported scale.', max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='AssessmentGroup',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('maximum_score', models.DecimalField(decimal_places=2, default=30, max_digits=7)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_groups', to='academics.courseoffering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessment_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='learning.assessmentgroup'),
        ),
    ]
