# Generated by Django 6.0.6 on 2026-09-23 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_course_classsession_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'academic_school_year',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.schoolyear')),
            ],
            options={
                'db_table': 'academic_semester',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('school_year', 'name'), name='unique_semester_per_year')],
            },
        ),
    ]
