# Generated by Django 6.1 on 2026-08-26 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.classsession')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCheckpoint',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkpoint_number', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_assignments', to=settings.AUTH_USER_MODEL)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['checkpoint_number'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_method', models.CharField(choices=[('QR_SCAN', 'QR Code Scan')], default='QR_SCAN', max_length=20)),
                ('status', models.CharField(default='PRESENT', max_length=20)),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='attendance.attendancecheckpoint')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'constraints': [models.UniqueConstraint(fields=('attendance_session', 'student'), name='unique_attendance_record')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancecheckpoint',
            constraint=models.UniqueConstraint(fields=('attendance_session', 'student'), name='unique_checkpoint_student'),
        ),
    ]
