# Generated by Django 6.1 on 2026-08-26 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecheckpoint',
            name='selection_method',
            field=models.CharField(choices=[('TEACHER', 'Selected by teacher'), ('AUTO', 'Auto-selected by system')], default='TEACHER', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='mode',
            field=models.CharField(choices=[('PROJECTOR', 'Projector (single QR)'), ('STATIONS', 'Student stations (multiple QR)')], default='STATIONS', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='verification_method',
            field=models.CharField(choices=[('QR_SCAN', 'QR Code Scan'), ('QR_STATION', 'Confirmed via own station'), ('MANUAL', 'Manually added by lecturer')], default='QR_SCAN', max_length=20),
        ),
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('AUTO_STATION', 'Auto-selected station'), ('TEACHER_STATION', 'Teacher-selected station'), ('SCAN', 'QR scan'), ('MANUAL', 'Manual entry')], max_length=20)),
                ('points', models.PositiveIntegerField(default=0)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_entries', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'attendance_session'), name='unique_points_per_session')],
            },
        ),
    ]
