# Generated by Django 6.1 on 2026-08-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancecheckpoint_selection_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsledger',
            name='category',
            field=models.CharField(choices=[('AUTO_STATION', 'Auto-selected station'), ('TEACHER_STATION', 'Teacher-selected station'), ('STATION_SCAN', 'Scan at a student station'), ('SCAN', 'QR scan'), ('MANUAL', 'Manual entry'), ('STUDENT_OF_CLASS', 'Student of the class')], max_length=20),
        ),
    ]
