# Generated by Django 6.1 on 2026-08-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_pointsledger_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='expected_headcount',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Optional: auto-closes session once this many unique students have checked in.', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='headcount_reached_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
